//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronicles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chronichlesEntities : DbContext
    {

        private static chronichlesEntities _context;
        public static chronichlesEntities GetContext()
        {
            if (_context == null)
                _context = new chronichlesEntities();

            return _context;
        }

        public chronichlesEntities()
            : base("name=chronichlesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Альпинисты> Альпинисты { get; set; }
        public virtual DbSet<Альпинисты_в_группах> Альпинисты_в_группах { get; set; }
        public virtual DbSet<Восхождения> Восхождения { get; set; }
        public virtual DbSet<Горы> Горы { get; set; }
        public virtual DbSet<Группы> Группы { get; set; }
        public virtual DbSet<Колво_восхождений_альпинистов> Колво_восхождений_альпинистов { get; set; }
        public virtual DbSet<Количество_возвождений> Количество_возвождений { get; set; }
        public virtual DbSet<Список_гор_на_которых_бывали_альпинисты> Список_гор_на_которых_бывали_альпинисты { get; set; }
    }
}
