//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronicles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Альпинисты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Альпинисты()
        {
            this.Альпинисты_в_группах = new HashSet<Альпинисты_в_группах>();
        }
    
        public int ID_Альпиниста { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
        public string Пол { get; set; }
        public string Фамилия_альпиниста { get; set; }
        public string Имя_альпиниста { get; set; }
        public string Отчество_альпиниста { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Альпинисты_в_группах> Альпинисты_в_группах { get; set; }
    }
}
