//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronicles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Альпинисты_в_группах
    {
        public int ID_Альпинисты_в_группах { get; set; }
        public Nullable<int> ID_Группы { get; set; }
        public Nullable<int> ID_Альпиниста { get; set; }
        public Nullable<System.DateTime> Дата_начала_возхождения { get; set; }
        public Nullable<System.DateTime> Дата_завершения_восхождения { get; set; }
    
        public virtual Альпинисты Альпинисты { get; set; }
        public virtual Группы Группы { get; set; }
    }
}
