//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronicles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Восхождения
    {
        public int ID_Восхождения { get; set; }
        public Nullable<int> ID_Горы { get; set; }
        public Nullable<int> ID_Группы { get; set; }
        public Nullable<System.DateTime> Дата_Возхождения { get; set; }
        public string Успешность { get; set; }
        public Nullable<int> Длительность { get; set; }
        public Nullable<int> Количество_вошедших { get; set; }
    
        public virtual Горы Горы { get; set; }
        public virtual Группы Группы { get; set; }
    }
}
