//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronicles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Список_гор_на_которых_бывали_альпинисты
    {
        public Nullable<int> ID_Группы { get; set; }
        public int ID_Альпиниста { get; set; }
        public string Фамилия_альпиниста { get; set; }
        public string Имя_альпиниста { get; set; }
        public string Отчество_альпиниста { get; set; }
        public Nullable<System.DateTime> Дата_Возхождения { get; set; }
        public string Название_Горы { get; set; }
    }
}
